# Generated by Django 6.0 on 2026-06-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True),
        ),
    ]
