# Generated by Django 6.0 on 2026-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(),
        ),
    ]
