# Generated by Django 6.0 on 2026-06-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_actor_movie_director_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(default=''),
        ),
    ]
